#
#  @(#) $Id: Makefile.config,v 1.3 2008/07/04 15:55:27 suikan Exp $
# 

#
#	Makefile のプロセッサ依存部（CORTEX-M3用）
#

#
#  ターゲットアーキテクチャの定義
#
TARGET = arm-none-eabi

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)
COPTS := $(COPTS) -Wall -g -O2 -march=armv7m -mthumb 

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) cpu_support.o
KERNEL_COBJS := $(KERNEL_COBJS) cpu_config.o

#
#  スタートアップモジュールに関する定義
#
START_OBJS = start.o

$(START_OBJS): %.o: %.S
	$(CC) -c $(CFLAGS) $(KERNEL_CFLAGS) $<

$(START_OBJS:.o=.d): %.d: %.S
	@$(PERL) $(SRCDIR)/utils/makedep -C $(CC) \
		-O "$(CFLAGS) $(KERNEL_CFLAGS)" $< >> Makefile.depend
