#
#  @(#) $Id: Makefile.config,v 1.5 2008/06/28 11:33:20 suikan Exp $
# 

#
#	Makefile のターゲットシステム依存部（CQ-SATARM : STM32F103VB用）
#

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(SRCDIR)/config/$(CPU)/$(SYS) \
			-I$(SRCDIR)/pdic/simple_sio
COPTS := $(COPTS) -msoft-float
LDFLAGS := $(LDFLAGS) -msoft-float

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(SRCDIR)/config/$(CPU)/$(SYS) \
				:$(SRCDIR)/pdic/simple_sio
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) 
KERNEL_COBJS := $(KERNEL_COBJS) sys_config.o usart.o

#
#  各セグメントの開始アドレスの定義
#  定義すると、jsp/configureが拾って、リンカのパラメータとして渡す。
#  (cq_starm.ld のMEMORYセクションで領域を明示的に宣言しているので、armv7m/cq_starmでは
#  セグメント開始アドレスはコメントアウトしている )
#
#TEXT_START_ADDRESS = 08003000
#DATA_START_ADDRESS = 20000000

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/$(SYS)/cq_starm.ld
